### ISSUE TITLE
Wrong URL on crates.io for the 'Homepage' and 'Repository' links

### ISSUE THREAD

**Issue by xpayn** [faradayio/boondock#9]
bookdock instead of boondock

**Comment by emk** [comment]
Thank you!

Fixed in GitHub, but not republished yet.

**Comment by tshepang** [comment]
I think it's worth publishing just for those fixes. I imagine a bunch of people already wasted a few minutes each before they finally got to this repo.

**Comment by emk** [comment]
Thanks! This should be fixed shortly. My apologies for the delay.
